package com.example.acousticsense.ui.duplex
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.*
import androidx.compose.ui.unit.dp
import com.example.acousticsense.duplex.*
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun DuplexScreen(state:DuplexUiState,onBack:()->Unit,onStart:()->Unit,onStop:()->Unit,onPulse:()->Unit,onRefresh:()->Unit,onBeginGuided:()->Unit,onNext:()->Unit,onComplete:(TestStatus)->Unit,onCancel:()->Unit,onExport:()->Unit){
 Scaffold(topBar={TopAppBar(title={Text("Laboratorio full-duplex")},navigationIcon={TextButton(onClick=onBack){Text("Volver")}})}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
 item{Text("Laboratorio de chirp y captura",style=MaterialTheme.typography.titleLarge,modifier=Modifier.semantics{heading()});Text("Experimental: no es una ayuda de movilidad. Usar con visión disponible, teléfono apoyado y sin caminar. El nivel digital no equivale a SPL seguro.")}
 item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Antes de comenzar",style=MaterialTheme.typography.titleMedium);Text("• Teléfono apoyado sobre una superficie estable\n• Visión disponible y ambiente relativamente silencioso\n• Volumen multimedia bajo\n• Bluetooth apagado y auriculares desconectados\n• Personas y mascotas alejadas del altavoz\n• No utilizar como ayuda de movilidad");Text("Esta prueba captura breves ventanas de audio alrededor de cada chirp. Los datos permanecen en el dispositivo y solo se guardan cuando elegís exportarlos. Evitá hablar durante la prueba.",style=MaterialTheme.typography.bodySmall)}}}
 item{Text("Permiso: ${if(state.permissionGranted)"concedido" else "no concedido"}");Text("Estado: ${state.state}",modifier=Modifier.semantics{liveRegion=LiveRegionMode.Polite});Text("Solicitado: LowLatency, Exclusive → Shared, mono Float, frecuencia natural, Unprocessed → VoiceRecognition")}
 item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick=onStart,enabled=state.permissionGranted&&state.state!=DuplexState.STARTED,modifier=Modifier.weight(1f).heightIn(min=56.dp)){Text("Iniciar")};Button(onClick=onStop,enabled=state.state in setOf(DuplexState.STARTED,DuplexState.STARTING,DuplexState.ERROR),modifier=Modifier.weight(1f).heightIn(min=56.dp)){Text("Detener")}}}
 item{Text("Perfil audible de laboratorio: 4–12 kHz · 10 ms · amplitud digital máxima 0,05 · Hann");Button(onClick=onPulse,enabled=state.canPulse,modifier=Modifier.fillMaxWidth().heightIn(min=56.dp).semantics{contentDescription="Emitir un único chirp audible de laboratorio"}){Text("Emitir un chirp")}}
 item{OutlinedButton(onClick=onRefresh,enabled=state.state==DuplexState.STARTED,modifier=Modifier.fillMaxWidth()){Text("Actualizar métricas")};Text("Configuración real y métricas conservadas (sin PCM):");Text("frames entrada=${state.engineSnapshot.metrics.framesRead}, salida=${state.engineSnapshot.metrics.framesWritten}, callbacks=${state.engineSnapshot.metrics.callbacks}, pulsos=${state.engineSnapshot.metrics.pulses}",style=MaterialTheme.typography.bodySmall);state.stopReason?.let{Text("Motivo de detención: $it")};state.lastError?.let{Text("Error: $it")}}
 item{HorizontalDivider();Text("Modo manual o batería guiada",style=MaterialTheme.typography.titleMedium);if(state.session==null)Button(onClick=onBeginGuided,modifier=Modifier.fillMaxWidth()){Text("Crear batería guiada")}}
 state.session?.let{s->item{Text("Sesión: ${s.sessionId}");s.results.forEach{result->Text("${result.definition.id}: ${result.status.name.lowercase()}");if(result.definition.id=="stability_session"&&result.status==TestStatus.RUNNING){val elapsed=(state.engineSnapshot.durationMillis).coerceAtMost(STABILITY_DURATION_MILLIS);Text("Transcurrido: ${elapsed/1000}s · Restante: ${(STABILITY_DURATION_MILLIS-elapsed)/1000}s");LinearProgressIndicator(progress={elapsed.toFloat()/STABILITY_DURATION_MILLIS},modifier=Modifier.fillMaxWidth())}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick=onNext){Text("Siguiente")};OutlinedButton(onClick={onComplete(TestStatus.PASSED)}){Text("Evaluar")};OutlinedButton(onClick={onComplete(TestStatus.INCONCLUSIVE)}){Text("Inconclusa")}};TextButton(onClick=onCancel){Text("Abortar / cancelar batería")}}}
 item{Button(onClick=onExport,modifier=Modifier.fillMaxWidth().heightIn(min=56.dp)){Text("Exportar informe JSON")};Text("El selector del sistema se abre solo por esta acción. No se guarda audio ni se usa Internet.",style=MaterialTheme.typography.bodySmall)}
 }}
}
