package com.example.acousticsense.duplex
class LaboratorySessionRunner(private val now:()->Long=System::currentTimeMillis) {
 fun create(id:String) = LaboratorySession(id,now(),events=listOf(SessionEvent(now(),"session_created","Batería creada en orden secuencial")))
 fun startNext(s:LaboratorySession):LaboratorySession { if(s.results.any{it.status==TestStatus.RUNNING}) return s; val i=s.results.indexOfFirst{it.status==TestStatus.PENDING}; if(i<0)return finish(s); return s.copy(results=s.results.updated(i,s.results[i].copy(status=TestStatus.RUNNING,startedAtMillis=now())),events=s.events+SessionEvent(now(),"test_started",s.results[i].definition.id)) }
 fun complete(s:LaboratorySession,status:TestStatus,message:String?=null):LaboratorySession { require(status in setOf(TestStatus.PASSED,TestStatus.FAILED,TestStatus.INCONCLUSIVE,TestStatus.SKIPPED));val i=s.results.indexOfFirst{it.status==TestStatus.RUNNING};if(i<0)return s;val next=s.copy(results=s.results.updated(i,s.results[i].copy(status=status,endedAtMillis=now(),message=message)),errors=if(status==TestStatus.FAILED)s.errors+"${s.results[i].definition.id}: ${message.orEmpty()}" else s.errors,events=s.events+SessionEvent(now(),"test_completed","${s.results[i].definition.id}: $status"));return if(next.results.none{it.status==TestStatus.PENDING})finish(next) else next }
 fun cancel(s:LaboratorySession):LaboratorySession { val results=s.results.map{if(it.status==TestStatus.RUNNING||it.status==TestStatus.PENDING)it.copy(status=TestStatus.ABORTED,endedAtMillis=now())else it};return finish(s.copy(results=results,events=s.events+SessionEvent(now(),"session_aborted","Cancelación explícita"))) }
 private fun finish(s:LaboratorySession):LaboratorySession { val p=s.results.count{it.status==TestStatus.PASSED};val f=s.results.count{it.status==TestStatus.FAILED};val i=s.results.count{it.status==TestStatus.INCONCLUSIVE};val a=s.results.count{it.status==TestStatus.ABORTED};val final=when{a>0->TestStatus.ABORTED;f>0->TestStatus.FAILED;i>0->TestStatus.INCONCLUSIVE;s.results.all{it.status==TestStatus.PASSED||it.status==TestStatus.SKIPPED}->TestStatus.PASSED;else->TestStatus.PENDING};return s.copy(endedAtMillis=if(final==TestStatus.PENDING)null else now(),summary=SessionSummary(p,f,i,a,final)) }
 private fun <T> List<T>.updated(i:Int,v:T)=toMutableList().also{it[i]=v}.toList()
}
