package com.example.acousticsense.duplex
object SessionJsonSerializer {
 const val SCHEMA_VERSION="1.0"
 fun serialize(session:LaboratorySession,appVersion:String,build:String,deviceJson:String,nativeSnapshot:String):String = buildString {
  append("{\"schemaVersion\":\"").append(SCHEMA_VERSION).append("\",\"sessionId\":\"").append(e(session.sessionId)).append("\",\"timestamps\":{\"startedAtMillis\":").append(session.startedAtMillis).append(",\"endedAtMillis\":").append(session.endedAtMillis?:"null").append("},\"appVersion\":\"").append(e(appVersion)).append("\",\"commitBuild\":\"").append(e(build)).append("\",\"device\":").append(deviceJson).append(",\"requestedConfiguration\":{\"performanceMode\":\"").append(session.requested.performanceMode).append("\",\"sharingMode\":\"").append(session.requested.sharingMode).append("\",\"sampleRateHz\":null,\"channelCount\":1,\"format\":\"Float\",\"inputPreset\":\"").append(session.requested.inputPreset).append("\"},\"actualConfigurationAndMetrics\":").append(nativeSnapshot).append(",\"results\":[")
  session.results.forEachIndexed{i,r->if(i>0)append(',');append("{\"id\":\"").append(r.definition.id).append("\",\"status\":\"").append(r.status.name.lowercase()).append("\",\"message\":").append(r.message?.let{"\"${e(it)}\""}?:"null").append('}')};append("],\"errors\":[");session.errors.forEachIndexed{i,v->if(i>0)append(',');append('"').append(e(v)).append('"')};append("],\"events\":[");session.events.forEachIndexed{i,v->if(i>0)append(',');append("{\"timestampMillis\":").append(v.timestampMillis).append(",\"type\":\"").append(e(v.type)).append("\",\"detail\":\"").append(e(v.detail)).append("\"}")};append("],\"summary\":{\"passed\":").append(session.summary.passed).append(",\"failed\":").append(session.summary.failed).append(",\"inconclusive\":").append(session.summary.inconclusive).append(",\"aborted\":").append(session.summary.aborted).append(",\"finalStatus\":\"").append(session.summary.finalStatus.name.lowercase()).append("\"}}")
 }
 private fun e(s:String)=s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n")
}
