#include "DuplexEngine.h"
#include <algorithm>
#include <cmath>
#include <chrono>
#include <sstream>
namespace { int64_t nowMillis(){ return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count(); } const char* api(oboe::AudioApi v){ return v==oboe::AudioApi::AAudio?"AAudio":v==oboe::AudioApi::OpenSLES?"OpenSL ES":"Unspecified"; } const char* sharing(oboe::SharingMode v){return v==oboe::SharingMode::Exclusive?"Exclusive":"Shared";} }
bool DuplexEngine::openOutput(oboe::SharingMode mode){ oboe::AudioStreamBuilder b; b.setDirection(oboe::Direction::Output)->setFormat(oboe::AudioFormat::Float)->setChannelCount(1)->setPerformanceMode(oboe::PerformanceMode::LowLatency)->setSharingMode(mode)->setDataCallback(this)->setErrorCallback(this); auto r=b.openStream(output_); if(r!=oboe::Result::OK){lastError_=oboe::convertToText(r); output_.reset(); return false;} outputShared_=mode==oboe::SharingMode::Shared; return true; }
bool DuplexEngine::openInput(oboe::SharingMode mode, oboe::InputPreset preset){ oboe::AudioStreamBuilder b; b.setDirection(oboe::Direction::Input)->setFormat(oboe::AudioFormat::Float)->setChannelCount(1)->setPerformanceMode(oboe::PerformanceMode::LowLatency)->setSharingMode(mode)->setInputPreset(preset); if(output_) b.setSampleRate(output_->getSampleRate()); auto r=b.openStream(input_); if(r!=oboe::Result::OK){lastError_=oboe::convertToText(r); input_.reset(); return false;} inputShared_=mode==oboe::SharingMode::Shared; inputPreset_=preset==oboe::InputPreset::Unprocessed?"Unprocessed":"VoiceRecognition"; return true; }
bool DuplexEngine::start(){ std::lock_guard<std::mutex> lock(lifecycleMutex_); if(running_) return true; disconnected_=false; readError_=false; lastError_.clear(); metrics_.reset(); if(!openOutput(oboe::SharingMode::Exclusive)&&!openOutput(oboe::SharingMode::Shared)){closeStreams();return false;} if(!openInput(oboe::SharingMode::Exclusive,oboe::InputPreset::Unprocessed)&&!openInput(oboe::SharingMode::Shared,oboe::InputPreset::Unprocessed)&&!openInput(oboe::SharingMode::Exclusive,oboe::InputPreset::VoiceRecognition)&&!openInput(oboe::SharingMode::Shared,oboe::InputPreset::VoiceRecognition)){closeStreams();return false;} signal_.configure(output_->getSampleRate()); running_=true; auto ir=input_->start(); auto out=output_->start(); if(ir!=oboe::Result::OK||out!=oboe::Result::OK){lastError_="No se pudieron iniciar ambos streams"; closeStreams();return false;} startedAtMillis_=nowMillis(); stoppedAtMillis_=0; starts_++; return true; }
void DuplexEngine::closeStreams(){ signal_.cancel(); if(output_){output_->stop();output_->close();output_.reset();} if(input_){input_->stop();input_->close();input_.reset();} running_=false; }
void DuplexEngine::stop(){ std::lock_guard<std::mutex> lock(lifecycleMutex_); if(!output_&&!input_) return; closeStreams(); stoppedAtMillis_=nowMillis(); stops_++; }
bool DuplexEngine::pulse() noexcept { if(!running_||!output_||!input_||output_->getState()!=oboe::StreamState::Started||input_->getState()!=oboe::StreamState::Started)return false; signal_.trigger(); metrics_.pulse(); return true; }
oboe::DataCallbackResult DuplexEngine::onAudioReady(oboe::AudioStream*,void* audioData,int32_t frames){ auto* out=static_cast<float*>(audioData); auto in=input_; int32_t read=0; if(in){int32_t wanted=std::min<int32_t>(frames,inputBuffer_.size()); auto result=in->read(inputBuffer_.data(),wanted,0); if(result) read=result.value(); else if(result.error()!=oboe::Result::ErrorTimeout){running_=false; readError_=true;}} metrics_.input(inputBuffer_.data(),read,frames); for(int32_t i=0;i<frames;i++)out[i]=signal_.next(); metrics_.output(frames); return running_?oboe::DataCallbackResult::Continue:oboe::DataCallbackResult::Stop; }
void DuplexEngine::onErrorAfterClose(oboe::AudioStream*,oboe::Result error){ disconnected_=error==oboe::Result::ErrorDisconnected; lastError_=oboe::convertToText(error); running_=false; }
std::string DuplexEngine::streamJson(const char* direction,const std::shared_ptr<oboe::AudioStream>& s,const char* preset) const { std::ostringstream o;o<<"{\"direction\":\""<<direction<<"\",\"requestedSampleRate\":null,\"hardwareSampleRate\":null,\"requestedChannelCount\":1,\"requestedPerformanceMode\":\"LowLatency\",\"requestedSharingMode\":\"Exclusive\"";if(!s)return o<<",\"state\":\"Closed\"}",o.str();o<<",\"state\":\""<<oboe::convertToText(s->getState())<<"\",\"api\":\""<<api(s->getAudioApi())<<"\",\"sampleRate\":"<<s->getSampleRate()<<",\"channelCount\":"<<s->getChannelCount()<<",\"hardwareChannelCount\":null,\"format\":\""<<oboe::convertToText(s->getFormat())<<"\",\"performanceMode\":\""<<oboe::convertToText(s->getPerformanceMode())<<"\",\"sharingMode\":\""<<sharing(s->getSharingMode())<<"\",\"framesPerBurst\":"<<s->getFramesPerBurst()<<",\"framesPerCallback\":"<<s->getFramesPerCallback()<<",\"bufferCapacity\":"<<s->getBufferCapacityInFrames()<<",\"bufferSize\":"<<s->getBufferSizeInFrames()<<",\"deviceId\":"<<s->getDeviceId()<<",\"sessionId\":"<<s->getSessionId()<<",\"inputPreset\":\""<<preset<<"\",\"xrunCount\":"<<s->getXRunCount().value_or(-1)<<"}";return o.str(); }
std::string DuplexEngine::snapshotJson(){ std::lock_guard<std::mutex> lock(lifecycleMutex_); int ix=input_?input_->getXRunCount().value_or(-1):-1, ox=output_?output_->getXRunCount().value_or(-1):-1;auto m=metrics_.snapshot(ix,ox);double db=m.rms>0?20*std::log10(m.rms):-120;std::ostringstream o;o<<"{\"running\":"<<(running_?"true":"false")<<",\"disconnected\":"<<(disconnected_?"true":"false")<<",\"starts\":"<<starts_<<",\"stops\":"<<stops_<<",\"startedAtMillis\":"<<startedAtMillis_<<",\"stoppedAtMillis\":"<<stoppedAtMillis_<<",\"durationMillis\":"<<(startedAtMillis_?((stoppedAtMillis_?stoppedAtMillis_.load():nowMillis())-startedAtMillis_):0)<<",\"lastError\":\""<<(readError_?"Error de lectura no bloqueante":lastError_)<<"\",\"output\":"<<streamJson("output",output_,"")<<",\"input\":"<<streamJson("input",input_,inputPreset_.c_str())<<",\"metrics\":{\"framesRead\":"<<m.framesRead<<",\"framesWritten\":"<<m.framesWritten<<",\"callbacks\":"<<m.callbacks<<",\"emptyReads\":"<<m.emptyReads<<",\"partialReads\":"<<m.partialReads<<",\"pulses\":"<<m.pulses<<",\"inputXruns\":"<<m.inputXruns<<",\"outputXruns\":"<<m.outputXruns<<",\"peak\":"<<m.peak<<",\"rms\":"<<m.rms<<",\"dbfs\":"<<db<<"}}";return o.str(); }
